const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Behaviors.Tween,
		C3.Behaviors.EightDir,
		C3.Behaviors.Physics,
		C3.Behaviors.solid,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{BtnLeft: 0},
	{BtnRigh: 0},
	{BtnGrab: 0},
	{Touch: 0},
	{Mouse: 0},
	{CanMove: 0},
	{MoveDir: 0},
	{Tween: 0},
	{"8Direction": 0},
	{Physics: 0},
	{Claw: 0},
	{Background: 0},
	{Solid: 0},
	{Playground: 0},
	{Wall_bottom: 0},
	{Wall_RL: 0},
	{Wall_head: 0},
	{Cat_head: 0},
	{Light: 0},
	{Carried: 0},
	{Gacha: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{PrizeShow: 0}
];

self.InstanceType = {
	BtnLeft: class extends self.ISpriteInstance {},
	BtnRigh: class extends self.ISpriteInstance {},
	BtnGrab: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Claw: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Playground: class extends self.ISpriteInstance {},
	Wall_bottom: class extends self.ISpriteInstance {},
	Wall_RL: class extends self.ISpriteInstance {},
	Wall_head: class extends self.ISpriteInstance {},
	Cat_head: class extends self.ISpriteInstance {},
	Light: class extends self.ISpriteInstance {},
	Gacha: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	PrizeShow: class extends self.ISpriteInstance {}
}